GET http://localhost:5000/post

###
GET http://localhost:5000/post/60a7f604e5de8a57e4e4ca7c HTTP/1.1

###
POST http://localhost:5000/user/signin HTTP/1.1
Content-Type: application/json

{
    "email": "sekato3722@slowimo.com",
    "password": "test123"
}

###
GET http://localhost:5000/post?&_limit=5&space=news_feed HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNla2F0bzM3MjJAc2xvd2ltby5jb20iLCJpZCI6IjYwYjcyYmE0YTViN2ZlNTMyMGQwNmFhZCIsImlhdCI6MTYyMjYzMjU0MH0.ayjU5EBmgq8epDsGIEyqIpRsUQbSFJRLyKmO4RL70-Q